### ISSUE TITLE
Incomplete documentation on how to configure static IP for TEP interfaces 

### ISSUE THREAD

**Issue by pradeep17j** [vmware/terraform-provider-nsxt#1174] opened 2024-04-04 17:52 UTC
### Describe the bug

While creating nsxt_edge_transport_node, 
if we have to do static IP assignment , there is no template which describes this in documentation.

In the example , it shows dhcp=true
resource "nsxt_edge_transport_node" "test" {
  description  = "Terraform-deployed edge node"
  display_name = "tf_edge_node"
  standard_host_switch {
    ip_assignment {
      assigned_by_dhcp = true
    }
    
    
   If we have to do dhcp=false and then static IP and guessed the config to look like below.
   But this did not work.
   
   resource "nsxt_edge_transport_node" "test1" {
  description  = "Terraform-deployed edge node"
  display_name = "tf_edge_node"
  standard_host_switch {
    ip_assignment {
      assigned_by_dhcp = false
      static_ip {
          ip_addresses = ["10.0.0.201","10.0.0.202","10.0.0.203" ]
          subnet_mask="255.255.255.0"
          default_gateway="10.0.0.250"
      }

   

### Reproduction steps

1. With terraform plan , I see failure like below
2.
3.
...2024-04-03T18:06:31.083-0700 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate
2024-04-03T18:06:31.084-0700 [DEBUG] State storage *statemgr.Filesystem declined to persist a state snapshot
2024-04-03T18:06:31.084-0700 [ERROR] vertex "nsxt_edge_transport_node.test1" error: failed to create Transport Node: error parsing HostSwitchSpec schema no valid IP assignment found
2024-04-03T18:06:31.084-0700 [TRACE] vertex "nsxt_edge_transport_node.test1": visit complete, with errors
2024-04-03T18:06:31.084-0700 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/vmware/nsxt\"] (close)" errored, so skipping
2024-04-03T18:06:31.084-0700 [TRACE] dag/walk: upstream of "root" errored, so skipping
2024-04-03T18:06:31.084-0700 [TRACE] statemgr.Filesystem: have already backed up original terraform.tfstate to terraform.tfstate.backup on a previous write
2024-04-03T18:06:31.084-0700 [TRACE] statemgr.Filesystem: state has changed since last snapshot, so incrementing serial to 9
2024-04-03T18:06:31.084-0700 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate
╷
│ Error: failed to create Transport Node: error parsing HostSwitchSpec schema no valid IP assignment found
│
│   with nsxt_edge_transport_node.test1,
│   on main.tf line 99, in resource "nsxt_edge_transport_node" "test1":
│   99: resource "nsxt_edge_transport_node" "test1" {
│
╵

### Expected behavior

Edge deploy plan should have succeeded

**Comment by ksamoray** [comment] 2024-04-07 09:32
IMO this is a duplicate of #1153 IMO, which will be resolved in the next release by PR #1161

**Comment by ksamoray** [comment] 2024-04-07 09:33
BTW specifying `assigned_by_dhcp = false` is redundant here.

**Comment by annakhm** [comment] 2024-05-03 17:45
This should be fixed with `3.6.1`, hence closing

**Closed by annakhm** 2024-05-03 17:45 UTC
Labels: bug
