### ISSUE TITLE
Configuration of TCP Clamping for IPSec VPN sessions via TF

### ISSUE THREAD

**Issue by hbechtel** [vmware/terraform-provider-nsxt#853] opened 2023-03-16 11:53 UTC
### Is your feature request related to a problem? Please describe.

I would like to configure VPN sessions via TF including the TCP clamping feature. In TF I always have to activate TCP Clamping (set the "direction") **and** set the maximum segment size ("max_segment_size"). As documented I must specify both when using TCP Clamping.

In the NSX-T UI I have the option just to activate TCP Clamping (set the "direction") without specifying the MSS which is a supported configuration (see https://docs.vmware.com/en/VMware-NSX-T-Data-Center/3.2/administration/GUID-5ADD0FBB-7F30-4933-8737-2AC0D919EE3F.html). In this case NSX-T uses a dynamic calculated MSS value (Web UI shows: "TCP MSS Value: Auto-assigned").

### Describe the solution you'd like

I would like to have the same options to configure the TCP clamping feature in TF as I have in the Web UI, explicitly I need the option to only set the "direction" and use the automaic calculated MSS value.

The reason that the configuration with only the direction set is invalid seems to be triggered by the behavior of the TF provider because it sends a MSS value of 0 (zero) to the API when there is no value specified:
`Error:  Failed to update IPSecVpnSession 21dd5a54-521b-4f16-8a89-f5f51c5e15b3: Field level validation errors: {value **0** of property tcp_mss_clamping.max_segment_size has violated the minimum valid value 108} (code 255)`

If the default for tcp_mss_clamping.max_segment_size would be "null" everything would be fine.

### Describe alternatives you've considered

---

### Additional context

---

**Comment by 2ez4szliu** [comment] 2023-04-24 18:11
The issue is resolved in PR #866 

Refer to https://github.com/vmware/terraform-provider-nsxt/blob/master/nsxt/resource_nsxt_policy_ipsec_vpn_session.go#L226

Line 226-236, if we initialize TcpMaximumSegmentSizeClamping object without specifying MaxSegmentSize then it will use the auto assigned TCP MSS value.

**Closed by 2ez4szliu** 2023-04-24 18:11 UTC
Labels: enhancement
